### ISSUE TITLE
`random_score` no longer supported?

### ISSUE THREAD

**Issue by rahearn** [toptal/chewy#605]
`MyIndex.random_score` appears to work with 0.9.0, but on 0.10.0 (and 0.10.1) I'm seeing:

```
[1] pry(main)> MyIndex.random_score
NoMethodError: undefined method `random_score' for MyIndex:Class
```

Is there a new way to get a random scoring?

**Comment by pyromaniac** [comment]
It is actually a filter, so use it inside the filter call.

**Comment by rahearn** [comment]
I'm not sure what you mean by use it inside the filter call.

I tried

* `MyIndex.filter { random_score }`
* `MyIndex.filter(:random_score)`
* `MyIndex.filter(random_score: {seed: Time.now.to_i})`

All of those fail in various ways.

**Comment by pyromaniac** [comment]
It should look like this: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-function-score-query.html#function-random

**Comment by rahearn** [comment]
OK, thanks. I got it working. It seems a lot more difficult to use now though. Is the `Chewy::Query` class going away?

**Comment by pyromaniac** [comment]
It will be probably back in some other form, but later
