### ISSUE TITLE
Newrelic logging returning undefined method `notice_sql` after upgrading newrelic_rpm to 4.x

### ISSUE THREAD

**Issue by Tongboy** [toptal/chewy#599]
Hi,

newrelic logging as described in the readme (https://github.com/toptal/chewy#newrelic-integration) was working great on 3.17 - upgraded to 4.5.x and now I"m receiving the following stack

```
Failure/Error: SearchIndex.reset!

NoMethodError:
  undefined method `notice_sql' for #<NewRelic::Agent::TransactionSampler:0x0000000a1d3530>
  Did you mean?  notice_push_frame
# ./config/initializers/chewy.rb:47:in `block (2 levels) in <top (required)>'
# /home/rof/cache/bundler/ruby/2.3.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/method_tracer.rb:74:in `block in trace_execution_scoped'
# /home/rof/cache/bundler/ruby/2.3.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/method_tracer_helpers.rb:26:in `trace_execution_scoped'
# /home/rof/cache/bundler/ruby/2.3.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/method_tracer.rb:72:in `trace_execution_scoped'
# ./config/initializers/chewy.rb:46:in `block in <top (required)>'
```

I reviewed the newrelic changelog and didn't notice any changes to the methods. anyone else having a similar problem or have any ideas?

Thank you!

**Comment by barthez** [comment]
Hello @Tongboy,

Thanks for bringing it up!

I was updating application to New Relic 4.x and had the same trouble. I've dug into NewRelic RPM code and mimicked the way they do instrumentation for ActiveRecord, here is a code:

```ruby
require 'new_relic/agent/instrumentation/evented_subscriber'

class ChewySubscriber < NewRelic::Agent::Instrumentation::EventedSubscriber
  def start(name, id, payload)
    event = ChewyEvent.new(name, Time.current, nil, id, payload)
    push_event(event)
  end

  def finish(_name, id, _payload)
    pop_event(id).finish
  end

  class ChewyEvent < NewRelic::Agent::Instrumentation::Event
    OPERATIONS = {
      'import_objects.chewy' => 'import',
      'search_query.chewy' => 'search',
      'delete_query.chewy' => 'delete'
    }.freeze

    def initialize(*args)
      super
      @segment = start_segment
    end

    def start_segment
      segment = NewRelic::Agent::Transaction::DatastoreSegment.new product, operation, collection, host, port
      if (txn = state.current_transaction)
        segment.transaction = txn
      end
      segment.notice_sql @payload[:request].to_s
      segment.start
      segment
    end

    def finish
      if (txn = state.current_transaction)
        txn.add_segment @segment
      end
      @segment.finish
    end

    private

    def state
      @state ||= NewRelic::Agent::TransactionState.tl_get
    end

    def product
      'Elasticsearch'
    end

    def operation
      OPERATIONS[name]
    end

    def collection
      payload.values_at(:type, :index)
        .reject { |value| value.try(:empty?) }
        .first
        .to_s
    end

    def host
      Chewy.client.transport.hosts.first[:host]
    end

    def port
      Chewy.client.transport.hosts.first[:port]
    end
  end
end

ActiveSupport::Notifications.subscribe(/.chewy$/, ChewySubscriber.new)
```

Thanks to this you can track ES performance as you would do for ActiveRecord, PostgreSQL, Mongo, Redis, etc.

I should definitely create PR to Chewy to update current README.

**Comment by Tongboy** [comment]
Thank @barthez !

Your code has been working great in our production environment - I'll put together a pull request to update the readme.

Thank you so much!
