### ISSUE TITLE
chewy:reset fails on parent indexes

### ISSUE THREAD

**Issue by Xanderwot** [toptal/chewy#334]
Hi all.

I have this lines in my chewy index file.
```ruby
define_type Relationship, name: 'follower' do
  root parent: 'user', parent_id: -> { subject_id } do
    field :id, type: 'integer'
  end
end

define_type Relationship, name: 'following' do
  root parent: 'user', parent_id: -> { object_id } do
    field :id, type: 'integer'
  end
end
```

My model:
```ruby
class Relationship < ActiveRecord::Base
  belongs_to :object, class_name: 'User'
  belongs_to :subject, class_name: 'User'

  update_index('users#follower') { self }
  update_index('users#following') { self }
end
```

If I clean up elasticsearch and run `rake chewy:reset` it works fine(all data passed to elastic).
But if I try recreate indexes (run another `rake chewy:reset` after the first one) it fails with:
```
NoMethodError: undefined method `[]' for nil:NilClass
/usr/local/bundle/gems/chewy-0.8.3/lib/chewy/type/import.rb:184:in `block in fetch_indexed_objects'
/usr/local/bundle/gems/chewy-0.8.3/lib/chewy/type/import.rb:183:in `map'
/usr/local/bundle/gems/chewy-0.8.3/lib/chewy/type/import.rb:183:in `fetch_indexed_objects'
/usr/local/bundle/gems/chewy-0.8.3/lib/chewy/type/import.rb:28:in `block (2 levels) in import'
/usr/local/bundle/gems/chewy-0.8.3/lib/chewy/type/adapter/active_record.rb:32:in `import_scope'
/usr/local/bundle/gems/chewy-0.8.3/lib/chewy/type/adapter/orm.rb:84:in `import'
/usr/local/bundle/gems/chewy-0.8.3/lib/chewy/type/import.rb:27:in `block in import'
```

Any ideas what I'm doing wrong? Thanks.

**Comment by pyromaniac** [comment]
Well, this looks like a bug, which ES version do you have?

**Comment by Xanderwot** [comment]
2.2.0

**Comment by pyromaniac** [comment]
Can you try to downgrade to 1.7.x? If it will work, then it seems like 2.2 support was not completely implemented :( And we have to figure out a patch

**Comment by Xanderwot** [comment]
Yep, it's works fine with 1.7.5.
Thanks. Waiting for patch...

**Comment by pyromaniac** [comment]
Well, you probably want to patch it by yourself :) This will significantly speed-up the process. It would be great if you will submit a PR

**Comment by Xanderwot** [comment]
You actually got this fix in master branch:

```ruby
parent = hit.has_key?('_parent') ? hit['_parent'] : hit['fields']['_parent']
indexed_objects[hit['_id']] = { parent: parent }
```
instead of:

```ruby
indexed_objects[hit['_id']] = { parent: hit['fields']['_parent'] }
``` 

When you planing release this feature? =)

**Comment by pyromaniac** [comment]
Well, I'll do it soon, could you use master for now instead? Master is quite stable

**Comment by Xanderwot** [comment]
Yep, I'm planning to do it. 
Thanks for your gem, it's really cool =)

**Comment by pyromaniac** [comment]
Thank you and you are welcome
